export const SET_NOTES_BUTTONS = "SET_NOTES_BUTTONS";
export const TOGGLE_NOTE_BUTTON = "TOGGLE_NOTE_BUTTON";
export const SET_TONALITIES = "SET_TONALITIES";
export const SET_TONALITIES_TO_VIEW = "SET_TONALITIES_TO_VIEW";